# Generated by Django 3.2.7 on 2021-12-18 04:53

import Metasite.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metasite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=150)),
                ('author', Metasite.models.AuthorField()),
                ('like_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('report_count', models.IntegerField(default=0)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('comments', Metasite.models.CommentsField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('author', Metasite.models.AuthorField()),
                ('like_count', models.IntegerField(default=0)),
                ('save_count', models.IntegerField(default=0)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('last_update_time', models.DateField(default=datetime.date.today)),
                ('body', models.CharField(default='', max_length=800)),
                ('comments', Metasite.models.CommentsField()),
                ('table_of_contents', models.CharField(default='', max_length=100)),
                ('labels', Metasite.models.LabelsField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', Metasite.models.ProfileField()),
                ('login_credential', Metasite.models.LoginCredentialField()),
                ('level', models.IntegerField(default=0)),
                ('ban_status', models.DateField(default=datetime.date.today)),
                ('like_history', Metasite.models.HistoryField()),
                ('collection', Metasite.models.HistoryField()),
                ('history', Metasite.models.HistoryField()),
                ('posts', Metasite.models.HistoryField()),
                ('reporteds', models.IntegerField(default=0)),
            ],
        ),
    ]
